"""Render tests for the two RPi Jinja templates.

The templates `alerts.py.j2` (40 stmts) and `msg.py.j2` (152 stmts) are
integration-tested via the `demol generate rpi` + riot-build path, which
is the only way to exercise their full content. This file renders them
in isolation to push pytest-cov line coverage on the template files
themselves. Templates are loaded via jinja2's FileSystemLoader with an
empty context (the templates have no Jinja directives, so the output
is the file content unchanged).
"""

import textwrap
from pathlib import Path

import pytest
from jinja2 import Environment, FileSystemLoader

TEMPLATES_DIR = Path(__file__).resolve().parents[1] / "demol" / "templates" / "rpi"


@pytest.fixture
def jinja_env():
    return Environment(
        loader=FileSystemLoader(str(TEMPLATES_DIR)),
        keep_trailing_newline=True,
    )


@pytest.mark.parametrize("template_name", ["alerts.py.j2", "msg.py.j2"])
def test_template_renders_without_context(jinja_env, template_name):
    """Templates have no Jinja directives, so empty context renders to source."""
    tpl = jinja_env.get_template(template_name)
    rendered = tpl.render()
    assert rendered
    assert len(rendered) > 100


def test_alerts_template_content_contains_alerttrigger(jinja_env):
    rendered = jinja_env.get_template("alerts.py.j2").render()
    assert "class AlertTrigger" in rendered
    assert "def evaluate" in rendered or "self.condition" in rendered
    assert "import logging" in rendered
    assert "import time" in rendered


def test_msg_template_content_contains_pubsubmessage_classes(jinja_env):
    rendered = jinja_env.get_template("msg.py.j2").render()
    assert "class DistanceMessage" in rendered
    assert "class EnvMessage" in rendered
    assert "PubSubMessage" in rendered
    assert "MessageHeader" in rendered


def test_msg_template_contains_typed_message_classes(jinja_env):
    rendered = jinja_env.get_template("msg.py.j2").render()
    for cls in [
        "DistanceMessage",
        "EnvMessage",
        "ProximityMessage",
        "ADCMessage",
        "LedArrayMessage",
    ]:
        assert f"class {cls}" in rendered, f"missing {cls}"


def test_msg_template_contains_extended_message_classes(jinja_env):
    rendered = jinja_env.get_template("msg.py.j2").render()
    for cls in [
        "TemperatureMessage",
        "HumidityMessage",
        "PressureMessage",
        "GasMessage",
        "AirQualityMessage",
        "LightMessage",
        "UVMessage",
        "SoundMessage",
    ]:
        assert f"class {cls}" in rendered, f"missing {cls}"


def test_alerts_template_uses_commlib(jinja_env):
    rendered = jinja_env.get_template("alerts.py.j2").render()
    assert "from commlib.node import Node" in rendered
    assert "from commlib.transports.mqtt import ConnectionParameters" in rendered


def test_msg_template_uses_commlib_msg(jinja_env):
    rendered = jinja_env.get_template("msg.py.j2").render()
    assert "from commlib.msg import MessageHeader, PubSubMessage" in rendered


def test_alerts_template_docstring_present(jinja_env):
    rendered = jinja_env.get_template("alerts.py.j2").render()
    assert "Generated by demol" in rendered
    assert "AlertTrigger" in rendered


def test_msg_template_docstring_present(jinja_env):
    rendered = jinja_env.get_template("msg.py.j2").render()
    assert "MessageHeader" in rendered
    assert "from commlib.msg import MessageHeader" in rendered


def test_msg_template_has_unused_import_or_pubsubmessage(jinja_env):
    rendered = jinja_env.get_template("msg.py.j2").render()
    assert "class LedArrayMessage" in rendered
    assert "0xFF0000" in rendered  # default colors


def test_alerts_template_has_cooldown_logic(jinja_env):
    """Cooldown gate is central to the AlertTrigger design."""
    rendered = jinja_env.get_template("alerts.py.j2").render()
    assert "cooldown" in rendered.lower()
    assert "last_fire" in rendered


def test_msg_template_message_classes_have_field_annotations(jinja_env):
    """Each PubSubMessage subclass has typed fields (the codegen contract)."""
    rendered = jinja_env.get_template("msg.py.j2").render()
    assert ": float =" in rendered
    assert ": int =" in rendered
    assert ": list =" in rendered


def test_alerts_template_defines_publish_payload_method(jinja_env):
    rendered = jinja_env.get_template("alerts.py.j2").render()
    assert "def _publish" in rendered or "publish" in rendered.lower()
