import pytest
import os
import shutil
from demol.lang.device import get_device_mm
from demol.transformations.m2m_smauto import demol2smauto

# Mock output directory
OUTPUT_DIR = "tests/output/smauto"


@pytest.fixture
def clean_output():
    if os.path.exists(OUTPUT_DIR):
        shutil.rmtree(OUTPUT_DIR)
    os.makedirs(OUTPUT_DIR)
    yield
    # shutil.rmtree(OUTPUT_DIR) # Keep for inspection if needed


def test_smauto_basic_transformation(clean_output):
    """Test basic transformation with Sensor (BME680) and MQTT Broker."""
    demol_str = """
    DEVICE TestDevice WITH
        description="Test Device",
        author="Tester",
        os=riotos;
    
    USE RaspberryPi_5_8GB;
    USE BME680 [EnvSensor];
    
    NETWORK [WiFi] WITH ssid="ssid", password="pass";
    
    BROKER [MQTT] MyBroker WITH
        host="localhost",
        port=1883,
        auth.username="user",
        auth.password="pass";
        
    CONNECT EnvSensor WITH
        POWER gnd -- GND_1, vcc -- power_5v_a
        DATA i2c [slave_address=0x77] sda sda -- GPIO2, scl scl -- GPIO3;
    """

    mm = get_device_mm()
    model = mm.model_from_str(demol_str)

    # Run transformation
    demol2smauto(model, output_dir=OUTPUT_DIR)

    # Verify file exists
    expected_file = os.path.join(OUTPUT_DIR, "TestDeviceSmAutoModel.auto")
    assert os.path.exists(expected_file)

    # Verify content
    with open(expected_file, "r") as f:
        content = f.read()

    assert "Broker<MQTT> MyBroker" in content
    assert 'host: "localhost"' in content
    assert "port: 1883" in content
    assert 'username: "user"' in content
    assert 'password: "pass"' in content

    assert "Entity EnvSensor" in content
    assert "type: sensor" in content.lower()
    # Topic is auto-generated by enrich_model: device_name.type.msg_type.instance_name
    assert 'topic: "testdevice.sensor.env.envsensor"' in content
    assert "broker: MyBroker" in content

    # Check attributes for Env message type
    assert "- temperature: float" in content
    assert "- pressure: float" in content
    assert "- humidity: float" in content
    assert "- gas_resistance: float" in content

    # BME680 doesn't have frequency attribute, so freq should be default 1
    assert "freq: 1" in content


def test_smauto_actuator_transformation(clean_output):
    """Test transformation with Actuator (LedGeneric)."""
    demol_str = """
    DEVICE ActuatorTest WITH
        description="Actuator Test",
        author="Tester",
        os=riotos;
    
    USE RaspberryPi_5_8GB;
    USE LedGeneric [StatusLed];
    
    NETWORK [WiFi] WITH ssid="ssid", password="pass";
    
    BROKER [MQTT] MyBroker WITH
        host="localhost",
        port=1883,
        auth.username="user",
        auth.password="pass";
        
    CONNECT StatusLed WITH
        POWER gnd -- GND_1, vcc -- power_3v3_a
        DATA gpio [mode="output"] vin -- GPIO18;
    """

    mm = get_device_mm()
    model = mm.model_from_str(demol_str)

    demol2smauto(model, output_dir=OUTPUT_DIR)

    expected_file = os.path.join(OUTPUT_DIR, "ActuatorTestSmAutoModel.auto")
    assert os.path.exists(expected_file)

    with open(expected_file, "r") as f:
        content = f.read()

    assert "Entity StatusLed" in content
    assert "type: actuator" in content.lower()

    # LedGeneric message type is "Led"
    assert "- state: bool" in content
    assert "- brightness: float" in content


def test_smauto_frequency_transformation(clean_output):
    """Test transformation with Sensor having frequency attribute (HCSR04P)."""
    demol_str = """
    DEVICE FreqTest WITH
        description="Freq Test",
        author="Tester",
        os=riotos;
    
    USE RaspberryPi_5_8GB;
    USE HCSR04P [DistSensor] WITH frequency=5;
    
    NETWORK [WiFi] WITH ssid="ssid", password="pass";
    
    BROKER [MQTT] MyBroker WITH
        host="localhost",
        port=1883,
        auth.username="user",
        auth.password="pass";
        
    CONNECT DistSensor WITH
        POWER GND -- GND_1, VCC -- power_3v3_a
        DATA gpio echo -- GPIO23, trigger -- GPIO24;
    """

    mm = get_device_mm()
    model = mm.model_from_str(demol_str)

    demol2smauto(model, output_dir=OUTPUT_DIR)

    expected_file = os.path.join(OUTPUT_DIR, "FreqTestSmAutoModel.auto")
    assert os.path.exists(expected_file)

    with open(expected_file, "r") as f:
        content = f.read()

    assert "Entity DistSensor" in content
    assert "type: sensor" in content.lower()

    # Check frequency
    assert "freq: 5" in content


def test_smauto_broker_variants(clean_output):
    """Test transformation with different Broker types (AMQP, Redis)."""
    # AMQP
    demol_str_amqp = """
    DEVICE AMQPTest WITH description="D", author="A", os=riotos;
    USE RaspberryPi_5_8GB;
    USE LedGeneric [Led];
    
    NETWORK [WiFi] WITH ssid="ssid", password="pass";
    
    BROKER [AMQP] AmqpBroker WITH
        host="localhost", port=5672,
        auth.username="u", auth.password="p",
        vhost="/", topicExchange="amq.topic";
    
    CONNECT Led WITH POWER gnd--GND_1, vcc--power_3v3_a DATA gpio[mode="output"] vin--GPIO18;
    """
    mm = get_device_mm()
    model = mm.model_from_str(demol_str_amqp)
    demol2smauto(model, output_dir=OUTPUT_DIR)

    with open(os.path.join(OUTPUT_DIR, "AMQPTestSmAutoModel.auto"), "r") as f:
        content = f.read()
    assert "Broker<AMQP> AmqpBroker" in content
    assert 'vhost: "/"' in content
    assert 'topicExchange: "amq.topic"' in content

    # Redis
    demol_str_redis = """
    DEVICE RedisTest WITH description="D", author="A", os=riotos;
    USE RaspberryPi_5_8GB;
    USE LedGeneric [Led];
    
    NETWORK [WiFi] WITH ssid="ssid", password="pass";
    
    BROKER [Redis] RedisBroker WITH
        host="localhost", port=6379,
        auth.username="u", auth.password="p",
        db=0;
    
    CONNECT Led WITH POWER gnd--GND_1, vcc--power_3v3_a DATA gpio[mode="output"] vin--GPIO18;
    """
    model = mm.model_from_str(demol_str_redis)
    demol2smauto(model, output_dir=OUTPUT_DIR)

    with open(os.path.join(OUTPUT_DIR, "RedisTestSmAutoModel.auto"), "r") as f:
        content = f.read()
    assert "Broker<Redis> RedisBroker" in content
    assert "db: 0" in content
