FROM python:3.10-slim

WORKDIR /api

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install fastapi uvicorn

# Copy the demol package
COPY demol /demol
# RUN pip install -e /demol

# Copy the API code
COPY api /api

# Set PYTHONPATH to include the root /app so imports work
ENV PYTHONPATH=/demol

# Expose port
EXPOSE 8000

# Run the API
CMD ["python", "main.py"]
