"""Abstract base class for code generators with model access.

This module provides a base class that all platform-specific code generators
(RPI, ESP, etc.) can inherit from to reuse common model querying functionality.
"""

from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any, Dict, List, Optional
import logging

import jinja2

logger = logging.getLogger(__name__)


class BaseCodeGenerator(ABC):
    """Abstract base class for code generators with direct model access.

    This class provides common functionality for querying textX device models
    and extracting information needed for code generation. Platform-specific
    generators should inherit from this class and implement the abstract methods.
    """

    def __init__(self, device_model, output_dir: Path):
        """Initialize generator with device model and output directory.

        Args:
            device_model: Parsed textX device model
            output_dir: Directory where generated code will be written
        """
        self.device_model = device_model
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    # ===== Common Model Query Methods =====

    def get_broker_config(self, broker: Any = None) -> Dict[str, Any]:
        """Query broker configuration from device model.

        Returns a dict that ALWAYS contains the legacy 4-tuple
        (host, port, ssl, username, password) so existing MQTT-only
        callers (RIOT mqtt_broker.c.j2, Zephyr prj.conf.j2) keep
        working unchanged. A new ``kind`` key ('amqp' | 'mqtt' |
        'redis') is added for T40-T45 to dispatch on.

        Per-broker-kind extra fields are also included when the
        grammar exposes them (e.g. vhost/topicExchange for AMQP,
        basePath/webPath/webPort for MQTT, db for Redis).

        When called with no args, returns the default broker's
        config (``self.device_model.broker``). When called with an
        explicit broker, returns that broker's config. No longer
        raises TypeError on non-MQTT brokers — the legacy behavior
        is preserved by leaving the legacy keys in place and adding
        new ones rather than by raising.
        """
        if broker is None:
            broker = self.device_model.broker
        if broker is None:
            return {"kind": "unknown", "host": "", "port": 0, "ssl": False, "username": "", "password": ""}

        type_name = type(broker).__name__
        if type_name.endswith("Broker"):
            kind = type_name[: -len("Broker")].lower()
        else:
            kind = "unknown"
        if kind not in ("amqp", "mqtt", "redis"):
            kind = "unknown"

        config = {
            "kind": kind,
            "host": broker.host,
            "port": broker.port,
            "ssl": getattr(broker, "ssl", False),
            "username": "",
            "password": "",
            "auth_key": "",
        }

        # Extract authentication (common to all 3 broker kinds).
        # The auth object is generated from the metamodel as a SimpleNamespace
        # (or one of the explicit Auth* classes if the user attached cert/key
        # metadata). We probe by attribute presence rather than class name
        # so we work regardless of which autogenerated class the parser
        # produced.
        auth = getattr(broker, "auth", None)
        if auth is not None:
            if hasattr(auth, "key") and getattr(auth, "key"):
                config["auth_key"] = getattr(auth, "key", "") or ""
            if hasattr(auth, "username"):
                config["username"] = getattr(auth, "username", "") or ""
            if hasattr(auth, "password"):
                config["password"] = getattr(auth, "password", "") or ""
            # If neither username/password nor key is set, leave the
            # config empty; backend templates decide whether to fall back
            # to env-var credentials.
        # Per-broker-kind optional fields.
        if kind == "amqp":
            config["vhost"] = getattr(broker, "vhost", "/")
            config["topic_exchange"] = getattr(broker, "topicE", "") or ""
            config["rpc_exchange"] = getattr(broker, "rpcE", "") or ""
        elif kind == "mqtt":
            config["base_path"] = getattr(broker, "basePath", "") or ""
            config["web_path"] = getattr(broker, "webPath", "") or ""
            config["web_port"] = getattr(broker, "webPort", 0) or 0
        elif kind == "redis":
            config["db"] = getattr(broker, "db", 0) or 0

        return config

    def get_board(self):
        """Query board from device model.

        Returns:
            Board object from the model
        """
        return self.device_model.components.board

    def get_connections(self) -> List[Any]:
        return list(self.device_model.connections)

    _FREQ_UNIT_TO_HZ = {
        "ghz": 1e9,
        "mhz": 1e6,
        "khz": 1e3,
        "hz": 1.0,
    }

    def get_sampling_config(self, instance_name: str) -> Optional[Dict[str, Any]]:
        """Look up SAMPLING config for a peripheral instance.

        Returns dict with keys: rate_hz, mode, buffer, threshold, rate, rate_unit
        or None if no SAMPLING declared for this instance.
        """
        samplings = getattr(self.device_model, "samplings", [])
        for s in samplings:
            target_name = getattr(s.target, "name", None)
            if target_name == instance_name:
                rate = float(s.rate) if s.rate else 1.0
                unit = str(s.rate_unit).lower() if s.rate_unit else "hz"
                rate_hz = rate * self._FREQ_UNIT_TO_HZ.get(unit, 1.0)
                return {
                    "rate": rate,
                    "rate_unit": unit,
                    "rate_hz": rate_hz,
                    "mode": getattr(s, "mode", None) or "continuous",
                    "buffer": getattr(s, "buffer", 0) or 0,
                    "threshold": getattr(s, "threshold", 0.0) or 0.0,
                }
        return None

    # ---- Alert helpers ----
    # Cooldown unit conversion: durations are in seconds.
    # NB: the grammar currently allows FrequencyUnit on COOLDOWN (e.g. "60 hz");
    # that is semantically wrong for a duration. We coerce hz/khz/mhz/ghz to
    # seconds with a warning so generated code keeps working, and document the
    # deprecation. New examples should use sec/min/hr.
    _COOLDOWN_UNIT_TO_SEC = {
        "sec": 1.0,
        "second": 1.0,
        "seconds": 1.0,
        "min": 60.0,
        "minute": 60.0,
        "minutes": 60.0,
        "hr": 3600.0,
        "hour": 3600.0,
        "hours": 3600.0,
    }

    def get_alerts_for_source(self, source_name: str) -> List[Any]:
        """Return alerts whose source is the named peripheral instance.

        Returns an empty list when the model has no alerts attribute or no
        alerts bind to the given source. Caller-side templates can iterate
        unconditionally on the result.
        """
        alerts = getattr(self.device_model, "alerts", None) or []
        return [a for a in alerts if getattr(a.source, "name", None) == source_name]

    def get_brokers(self) -> List[Any]:
        """Return all brokers declared in the model."""
        return list(getattr(self.device_model, "brokers", []) or [])

    def resolve_broker(self, name: Optional[str]) -> Any:
        """Look up a broker by its declared name.

        When ``name`` is None, returns the model's default/first broker
        (i.e. ``device_model.broker``). Raises KeyError when the name is
        provided but no matching broker exists, so generators fail loudly
        rather than producing silently broken runtimes.
        """
        if name is None:
            return self.device_model.broker
        for b in self.get_brokers():
            if getattr(b, "name", None) == name:
                return b
        raise KeyError(f"Broker '{name}' not declared in model")

    def cooldown_to_seconds(self, value: Optional[float], unit: Optional[str]) -> float:
        """Coerce an alert COOLDOWN to wall-clock seconds.

        Returns 0.0 when no cooldown is declared. ``hz``/``khz``/``mhz``/``ghz``
        units are treated as ``sec`` with a logged warning (see class comment).
        """
        if not value:
            return 0.0
        unit_norm = (unit or "sec").lower()
        if unit_norm in self._COOLDOWN_UNIT_TO_SEC:
            return float(value) * self._COOLDOWN_UNIT_TO_SEC[unit_norm]
        if unit_norm in self._FREQ_UNIT_TO_HZ:
            logger.warning(
                "Alert COOLDOWN unit '%s' is a frequency, not a duration; "
                "treating value as seconds. Use sec/min/hr instead.",
                unit_norm,
            )
            return float(value)
        logger.warning("Unknown COOLDOWN unit '%s'; treating value as seconds.", unit_norm)
        return float(value)

    def resolve_activate_target_topic(self, target) -> Optional[str]:
        """Find the connection topic an ACTIVATE target subscribes to.

        Returns the ``CONNECT @ "topic"`` for the target peripheral instance,
        or None when the target has no connection (in which case the alert
        action will be skipped at codegen time).
        """
        target_name = getattr(target, "name", None)
        for conn in self.get_connections():
            if getattr(conn.peripheral, "name", None) == target_name:
                return getattr(conn, "remote", None)
        return None

    # Signed integer types used to cast scaled literals in RIOT condition rendering.
    _RIOT_INT_TYPES = {"int8", "uint8", "int16", "uint16", "int32", "uint32", "int64", "uint64"}

    _RIOT_COMP_OPS = {">": ">", "<": "<", ">=": ">=", "<=": "<=", "==": "==", "!=": "!="}

    def get_alert_property_resolver(self, peripheral_ref, target: str = "riotos") -> Dict[str, Dict[str, Any]]:
        """Build {property_name: {expr, scale, ptype}} from a peripheral's PROPERTIES.

        Selects the entry tagged ``FOR <target>`` first; falls back to the
        untagged (default) entry when the target-specific one is absent. Returns
        an empty dict when the peripheral declares no properties (alert codegen
        for this peripheral on this target should then be skipped with a warning).
        """
        resolver: Dict[str, Dict[str, Any]] = {}
        properties = getattr(peripheral_ref, "properties", None) or []
        # Two passes: tagged-for-target wins over untagged default.
        for prop in properties:
            if getattr(prop, "target", None) == target:
                resolver[prop.name] = {
                    "expr": prop.expr,
                    "scale": getattr(prop, "scale", 0) or 0,
                    "ptype": prop.ptype,
                }
        for prop in properties:
            if getattr(prop, "target", None) is None and prop.name not in resolver:
                resolver[prop.name] = {
                    "expr": prop.expr,
                    "scale": getattr(prop, "scale", 0) or 0,
                    "ptype": prop.ptype,
                }
        return resolver

    def render_riot_comparison(self, comparison, resolver: Dict[str, Dict[str, Any]]) -> Optional[str]:
        """Render a single AlertComparison as a C boolean expression.

        Returns None when the property is not declared in the resolver (the
        caller should drop the entire alert with a warning to keep generated
        code honest about what the driver actually exposes).
        """
        prop_name = comparison.property
        info = resolver.get(prop_name)
        if info is None:
            return None
        op_src = comparison.op
        op_c = self._RIOT_COMP_OPS.get(op_src)
        if op_c is None:
            return None
        scale = info["scale"] or 1
        value = comparison.value * scale
        ptype = info["ptype"]
        if ptype in self._RIOT_INT_TYPES:
            literal = f"(int64_t)({int(round(value))})"
        else:
            literal = repr(float(value))
        return f"({info['expr']}) {op_c} {literal}"

    def render_riot_condition(self, expr, resolver: Dict[str, Dict[str, Any]]) -> Optional[str]:
        """Recursively render an AlertConditionExpr as a C boolean expression.

        Returns None if any leaf comparison cannot be rendered (unknown
        property), so the caller can skip the whole alert atomically.
        """
        left = expr.left
        rendered_left = self.render_riot_comparison(left, resolver)
        if rendered_left is None:
            return None
        op = getattr(expr, "op", None)
        right = getattr(expr, "right", None)
        if not op or right is None:
            return rendered_left
        rendered_right = self.render_riot_condition(right, resolver)
        if rendered_right is None:
            return None
        c_op = "&&" if op == "&&" else "||"
        return f"({rendered_left}) {c_op} ({rendered_right})"

    def get_peripheral_attributes(self, peripheral_ref) -> Dict[str, Any]:
        """Extract attributes from peripheral definition and instance.

        Args:
            peripheral_ref: Reference to peripheral object (type) or ComponentInstance

        Returns:
            Dictionary of attribute name-value pairs
        """
        result = {}

        # Determine if we have a ComponentInstance or a Peripheral (type)
        if hasattr(peripheral_ref, "ref"):
            # It's a ComponentInstance (e.g., from USE statement)
            instance = peripheral_ref
            type_ref = instance.ref

            # 1. Start with default values from the type definition (.hwd)
            for item in type_ref.attributes:
                result[item.name] = self._convert_attribute_value(item.default)

            # 2. Override with values from the instance definition (.dev)
            for attr_set in instance.attributes:
                result[attr_set.name] = self._convert_attribute_value(attr_set.value)
        else:
            # It's just the Peripheral type reference
            for item in peripheral_ref.attributes:
                result[item.name] = self._convert_attribute_value(item.default)

        return result

    def get_platform_attributes(self, obj, os_name: str) -> Dict[str, Any]:
        """Extract platform-specific attributes for a given OS.

        Args:
            obj: Object with platforms attribute (e.g., Board)
            os_name: Name of the operating system (e.g., 'riotos', 'raspbian')

        Returns:
            Dictionary of attribute name-value pairs
        """
        result = {}
        if hasattr(obj, "platforms") and obj.platforms:
            for platform in obj.platforms:
                if platform.os == os_name:
                    for attr in platform.attributes:
                        result[attr.name] = self._convert_attribute_value(attr.value)
                    break
        return result

    def get_operational_attributes(self, peripheral_ref) -> Dict[str, Any]:
        """Extract operational attributes from peripheral definition.

        Args:
            peripheral_ref: Reference to peripheral object with operational block

        Returns:
            Dictionary of operational attribute name-value pairs
        """
        op = peripheral_ref.operational
        result = {
            "vcc": op.vcc,
            "ioVcc": getattr(op, "iovcc", op.vcc),
        }

        # Add power consumption if present
        if hasattr(op, "min") and op.min:
            result["power_min"] = {"value": op.min.value, "unit": op.min.unit}
        if hasattr(op, "max") and op.max:
            result["power_max"] = {"value": op.max.value, "unit": op.max.unit}
        if hasattr(op, "avg") and op.avg:
            result["power_avg"] = {"value": op.avg.value, "unit": op.avg.unit}

        # Add frequency if present
        if hasattr(op, "freq_max") and op.freq_max:
            result["freq_max"] = {"value": op.freq_max.value, "unit": op.freq_max.unit}

        return result

    def get_pin_mappings(self, connection, board) -> Dict[str, Any]:
        """Extract pin mappings from data connections.

        Args:
            connection: Connection object
            board: Board object for pin lookups

        Returns:
            Dictionary containing pin mappings and properties by connection type
        """
        pins = {}
        board_pins_map = {pin.name: pin for pin in board.pins}

        data_connections = connection.dataConns if hasattr(connection, "dataConns") else connection

        for data_conn in data_connections:
            conn_type = data_conn.type

            if conn_type == "gpio":
                pins.update(self._extract_gpio_pins(connection, data_conn, board_pins_map))
            elif conn_type == "i2c":
                pins.update(self._extract_i2c_pins(connection, data_conn, board_pins_map))
            elif conn_type == "spi":
                pins.update(self._extract_spi_pins(connection, data_conn, board_pins_map))
            elif conn_type == "uart":
                pins.update(self._extract_uart_pins(connection, data_conn, board_pins_map))
            elif conn_type == "pwm":
                pins.update(self._extract_pwm_pins(connection, data_conn, board_pins_map))
            else:
                raise TypeError(f"Not a valid IO Connection Type: {conn_type}")

        return pins

    # ===== Helper Methods for Pin Extraction =====

    def _extract_gpio_pins(self, conn, data_conn, board_pins_map) -> Dict[str, Any]:
        """Extract GPIO pin mappings and properties."""
        pins = {}

        # Extract GPIO properties
        gpio_props = {}
        for prop in data_conn.props:
            if prop.name in ["mode", "pullup", "pulldown"]:
                gpio_props[prop.name] = self._convert_attribute_value(prop.value)

        # Handle pins based on peripheral pin name
        for pin_map in data_conn.pins:
            board_pin, periph_pin = self._get_board_and_periph_pins(conn, pin_map)
            pins[periph_pin] = board_pin
            pins[f"{periph_pin}_props"] = gpio_props

        return pins

    def _extract_i2c_pins(self, conn, data_conn, board_pins_map) -> Dict[str, Any]:
        """Extract I2C pin mappings, bus info, and properties."""
        pins = {}

        # Extract I2C properties
        i2c_props = {}
        for prop in data_conn.props:
            if prop.name in ["slave_address", "bus_speed"]:
                i2c_props[prop.name] = self._convert_attribute_value(prop.value)

        for pin_map in data_conn.pins:
            board_pin_name, periph_pin_name = self._get_board_and_periph_pins(conn, pin_map)
            board_pin = board_pins_map.get(board_pin_name)

            if pin_map.function == "sda":
                pins["sda"] = board_pin_name
                # Extract I2C bus from board pin's function definition
                if board_pin:
                    pins["i2c_bus"] = self._get_bus_from_pin(board_pin, "sda")
            elif pin_map.function == "scl":
                pins["scl"] = board_pin_name
            pins[f"{pin_map.function}_props"] = i2c_props

        return pins

    def _extract_spi_pins(self, conn, data_conn, board_pins_map) -> Dict[str, Any]:
        """Extract SPI pin mappings, bus info, and properties."""
        pins = {}

        # Extract SPI properties
        spi_props = {}
        for prop in data_conn.props:
            if prop.name in ["bus_speed", "mode"]:
                spi_props[prop.name] = self._convert_attribute_value(prop.value)

        for pin_map in data_conn.pins:
            board_pin_name, periph_pin_name = self._get_board_and_periph_pins(conn, pin_map)
            board_pin = board_pins_map.get(board_pin_name)

            if pin_map.function == "mosi":
                pins["mosi"] = board_pin_name
                # Extract SPI bus from board pin's function definition
                if board_pin:
                    pins["spi_bus"] = self._get_bus_from_pin(board_pin, "mosi")
            elif pin_map.function == "miso":
                pins["miso"] = board_pin_name
            elif pin_map.function == "sck":
                pins["sck"] = board_pin_name
            elif pin_map.function == "cs":
                pins["cs"] = board_pin_name
            pins[f"{pin_map.function}_props"] = spi_props

        return pins

    def _extract_uart_pins(self, conn, data_conn, board_pins_map) -> Dict[str, Any]:
        """Extract UART pin mappings, port info, and properties."""
        pins = {}

        # Extract UART properties
        uart_props = {}
        for prop in data_conn.props:
            if prop.name in ["baudrate", "parity", "stop_bits", "data_bits"]:
                uart_props[prop.name] = self._convert_attribute_value(prop.value)

        for pin_map in data_conn.pins:
            board_pin_name, periph_pin_name = self._get_board_and_periph_pins(conn, pin_map)
            board_pin = board_pins_map.get(board_pin_name)

            if pin_map.function == "tx":
                pins["tx"] = board_pin_name
                # Extract UART port from board pin's function definition
                if board_pin:
                    pins["uart_port"] = self._get_bus_from_pin(board_pin, "tx")
            elif pin_map.function == "rx":
                pins["rx"] = board_pin_name
            pins[f"{pin_map.function}_props"] = uart_props

        return pins

    def _extract_pwm_pins(self, conn, data_conn, board_pins_map) -> Dict[str, Any]:
        """Extract PWM pin mappings and properties."""
        pins = {}

        # Extract PWM properties
        pwm_props = {}
        for prop in data_conn.props:
            if prop.name in ["frequency", "duty_cycle", "channel"]:
                pwm_props[prop.name] = self._convert_attribute_value(prop.value)

        # Handle pins based on peripheral pin name
        for pin_map in data_conn.pins:
            board_pin_name, periph_pin_name = self._get_board_and_periph_pins(conn, pin_map)
            board_pin = board_pins_map.get(board_pin_name)

            pins[periph_pin_name] = board_pin_name
            pins[f"{periph_pin_name}_props"] = pwm_props

            # Extract PWM channel from board pin's function definition if not in props
            if board_pin and "channel" not in pwm_props:
                pwm_channel = self._get_channel_from_pin(board_pin, "pwm")
                if pwm_channel is not None:
                    pins["pwm_channel"] = pwm_channel

        return pins

    def _get_board_and_periph_pins(self, conn, pin_map):
        """Helper to identify which pin is the board pin and which is the peripheral pin."""
        from_comp = conn.from_comp
        _ = conn.to_comp

        # Check if from_comp is the board
        is_from_board = False
        if hasattr(from_comp, "ref"):
            if type(from_comp.ref).__name__ == "BoardDef":
                is_from_board = True
        elif type(from_comp).__name__ == "BoardDef":
            is_from_board = True

        if is_from_board:
            return pin_map.fromPin, pin_map.toPin
        else:
            return pin_map.toPin, pin_map.fromPin

    def _get_bus_from_pin(self, board_pin, function_type: str) -> int:
        """Extract bus/port number from board pin's function definition.

        Args:
            board_pin: Board pin object with funcs attribute
            function_type: Type of function to look for (e.g., 'sda', 'mosi', 'tx')

        Returns:
            Bus/port number as integer, defaults to 0 if not found
        """
        if hasattr(board_pin, "funcs"):
            for func in board_pin.funcs:
                # Check if this function matches the type we're looking for
                if hasattr(func, "ptype") and func.ptype == function_type:
                    # Return the bus number from the function definition
                    if hasattr(func, "bus"):
                        return int(func.bus)
        return 0

    def _get_channel_from_pin(self, board_pin, function_type: str) -> Optional[int]:
        """Extract channel number from board pin's function definition.

        Args:
            board_pin: Board pin object with funcs attribute
            function_type: Type of function to look for (e.g., 'pwm')

        Returns:
            Channel number as integer, or None if not found
        """
        if hasattr(board_pin, "funcs"):
            for func in board_pin.funcs:
                # Check if this function matches the type we're looking for
                if hasattr(func, "ptype") and func.ptype == function_type:
                    # Return the channel number from the function definition
                    if hasattr(func, "channel"):
                        return int(func.channel)
        return None

    def _convert_attribute_value(self, value) -> Any:
        """Convert AttributeValue to Python object.

        Args:
            value: AttributeValue object from model

        Returns:
            Python object (list, dict, or primitive)
        """
        v_type = type(value).__name__
        if v_type == "ListValue":
            return [self._convert_attribute_value(v) for v in value.items]
        elif v_type == "DictValue":
            return {item.key: self._convert_attribute_value(item.value) for item in value.items}
        elif v_type == "AttributeSet":
            return {attr.name: self._convert_attribute_value(attr.value) for attr in value.attributes}
        else:
            # VALUE (HEX, NUMBER, STRING, BOOL)
            if isinstance(value, str) and value.lower().startswith("0x"):
                try:
                    return int(value, 16)
                except ValueError:
                    return value
            return value

    def _build_conn_info(self, pins: Dict[str, Any], board) -> Dict[str, Any]:
        """Build structured connection information dictionary.

        Args:
            pins: Pin mappings dictionary
            board: Board object

        Returns:
            Structured connection dictionary organized by type
        """
        conn = {}
        board_pins_map = {pin.name: pin for pin in board.pins}

        # GPIO connection
        gpio_pins = {}
        gpio_props = {}
        for key, value in pins.items():
            if key.endswith("_props") and "gpio" in key.lower():
                gpio_props.update(value if isinstance(value, dict) else {})
            elif not key.endswith("_props") and key not in [
                "sda",
                "scl",
                "mosi",
                "miso",
                "sck",
                "cs",
                "tx",
                "rx",
                "i2c_bus",
                "spi_bus",
                "uart_port",
            ]:
                # Add pin name and id
                board_pin = board_pins_map.get(value)
                gpio_pins[key] = {
                    "name": value,
                    "id": board_pin.number if board_pin else None,
                }

        if gpio_pins or gpio_props:
            conn["gpio"] = {**gpio_props, "pins": gpio_pins}

        # I2C connection
        if "sda" in pins or "scl" in pins:
            i2c_pins = {}
            i2c_props = {}
            if "i2c_bus" in pins:
                i2c_props["bus"] = pins["i2c_bus"]

            # Add SDA pin with id
            if "sda" in pins:
                board_pin = board_pins_map.get(pins["sda"])
                i2c_pins["sda"] = {
                    "name": pins["sda"],
                    "id": board_pin.number if board_pin else None,
                }

            # Add SCL pin with id
            if "scl" in pins:
                board_pin = board_pins_map.get(pins["scl"])
                i2c_pins["scl"] = {
                    "name": pins["scl"],
                    "id": board_pin.number if board_pin else None,
                }

            # Add I2C properties
            for key, value in pins.items():
                if "sda_props" in key or "scl_props" in key:
                    i2c_props.update(value if isinstance(value, dict) else {})
            conn["i2c"] = {**i2c_props, "pins": i2c_pins}

        # SPI connection
        if "mosi" in pins or "miso" in pins or "sck" in pins:
            spi_pins = {}
            spi_props = {}
            if "spi_bus" in pins:
                spi_props["bus"] = pins["spi_bus"]

            # Add pin mappings with ids
            for pin_name in ["mosi", "miso", "sck", "cs"]:
                if pin_name in pins:
                    board_pin = board_pins_map.get(pins[pin_name])
                    spi_pins[pin_name] = {
                        "name": pins[pin_name],
                        "id": board_pin.number if board_pin else None,
                    }

            # Add SPI properties
            for key, value in pins.items():
                if any(x in key for x in ["mosi_props", "miso_props", "sck_props", "cs_props"]):
                    spi_props.update(value if isinstance(value, dict) else {})
            conn["spi"] = {**spi_props, "pins": spi_pins}

        # UART connection
        if "tx" in pins or "rx" in pins:
            uart_pins = {}
            uart_props = {}
            if "uart_port" in pins:
                uart_props["port"] = pins["uart_port"]

            # Add TX pin with id
            if "tx" in pins:
                board_pin = board_pins_map.get(pins["tx"])
                uart_pins["tx"] = {
                    "name": pins["tx"],
                    "id": board_pin.number if board_pin else None,
                }

            # Add RX pin with id
            if "rx" in pins:
                board_pin = board_pins_map.get(pins["rx"])
                uart_pins["rx"] = {
                    "name": pins["rx"],
                    "id": board_pin.number if board_pin else None,
                }

            # Add UART properties
            for key, value in pins.items():
                if "tx_props" in key or "rx_props" in key:
                    uart_props.update(value if isinstance(value, dict) else {})
            conn["uart"] = {**uart_props, "pins": uart_pins}

        # PWM connection
        pwm_pins = {}
        pwm_props = {}
        for key, value in pins.items():
            if key.endswith("_props") and "pwm" in key.lower():
                pwm_props.update(value if isinstance(value, dict) else {})
            elif not key.endswith("_props") and key not in [
                "sda",
                "scl",
                "mosi",
                "miso",
                "sck",
                "cs",
                "tx",
                "rx",
                "i2c_bus",
                "spi_bus",
                "uart_port",
                "pwm_channel",
            ]:
                # Check if this is a PWM pin (not already handled by other connection types)
                if key not in gpio_pins:
                    board_pin = board_pins_map.get(value)
                    if board_pin:
                        # Check if pin has PWM functionality
                        has_pwm = False
                        if hasattr(board_pin, "funcs"):
                            for func in board_pin.funcs:
                                if hasattr(func, "ptype") and "pwm" in str(func.ptype).lower():
                                    has_pwm = True
                                    break
                        if has_pwm:
                            pwm_pins[key] = {
                                "name": value,
                                "id": board_pin.number if board_pin else None,
                            }

        if "pwm_channel" in pins:
            pwm_props["channel"] = pins["pwm_channel"]

        if pwm_pins or pwm_props:
            conn["pwm"] = {**pwm_props, "pins": pwm_pins}

        return conn

    # ===== Template Rendering (Shared) =====

    def _write_template(self, template: jinja2.Template, context: Dict[str, Any], output_path: Path) -> None:
        """Render template and write to file (UTF-8)."""
        output = template.render(**context)

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(output)

        logger.debug(f"Generated: {output_path}")

    # ===== Abstract Methods (Platform-Specific) =====

    @abstractmethod
    def generate(self) -> None:
        """Generate code for target platform.

        This method should orchestrate the entire code generation process,
        calling other generation methods as needed.
        """
        pass

    @abstractmethod
    def setup_template_environment(self) -> jinja2.Environment:
        """Setup Jinja2 environment with platform-specific templates.

        Returns:
            Configured Jinja2 Environment object
        """
        pass

    OS = ""

    def os_name(self) -> str:
        """Return the target operating system identifier (e.g. "raspbian", "riotos")."""
        return self.OS

    # ------------------------------------------------------------------
    # CONSTRAINT runtime helpers
    # ------------------------------------------------------------------
    #
    # These helpers are the foundation of the user-defined CONSTRAINT
    # codegen path.  T11/T12/T13 add the per-backend emission logic that
    # actually wires ``get_constraint_runtime_check`` output into the
    # generated ``<peripheral>.py`` / ``<peripheral>.c`` template.
    #
    # Design goals:
    #   * Backend-agnostic entry point: ``get_constraint_runtime_check`` /
    #     ``render_constraint_predicate`` always exist on the base class
    #     and dispatch on the ``backend`` string.
    #   * Subclass-overridable leaves: each backend can replace the
    #     Python or C renderer (and the helper-function table) without
    #     having to copy the dispatch logic.
    #   * Defensive AST traversal: textX collapses some rules at parse
    #     time, so the renderer is tolerant of the AdditiveExpr vs
    #     MultiplicativeExpr-vs-atom collapse pattern observed in
    #     ``user_constraints._eval_*``.

    # Per-kind integer codes used by C runtime helpers.  Mirrors the
    # ``kind`` field populated by the RIOT/Zephyr codegen (see
    # ``docs/constraint-runtime-design.md`` §6).
    _CONSTRAINT_KIND_CODES = {
        "SENSOR": 0,
        "ACTUATOR": 1,
        "PERIPHERAL": 2,
        "CONNECTION": 3,
    }

    def _get_constraint_functions(self) -> Dict[str, str]:
        """Return the table of runtime helper names, keyed by DSL builtin.

        The base implementation targets C runtimes (RIOT, Zephyr) — every
        backend's runtime names those four helpers ``count_*`` /
        ``*_power_mW``.  The RPi generator overrides this in T11 to
        return raw Python builtin names (e.g. ``"count": "count"``).

        Subclasses may also override individual entries via the
        ``_get_constraint_functions`` hook to point at driver-local
        helpers (e.g. ``peripheral_count_kind(kind)``).

        Returns:
            Mapping ``{count, sum_power, avg_power, max_power}`` ->
            runtime function name as a string.
        """
        return {
            "count": "count_peripherals",
            "sum_power": "sum_power_mW",
            "avg_power": "avg_power_mW",
            "max_power": "max_power_mW",
        }

    def get_constraint_runtime_check(self, model, backend: Optional[str] = None) -> str:
        """Emit a runtime ``check_constraints()`` block for ``model``.

        The output is a multi-line string suitable for splicing into a
        backend template.  It declares the runtime helper functions the
        predicates rely on and iterates over ``model.constraints``,
        rendering one check per CONSTRAINT block.  Models with no
        constraints produce an empty string so the generators can call
        this method unconditionally.

        Args:
            model: The parsed textX device model.
            backend: Optional backend tag (``"raspbian"``, ``"riotos"``,
                ``"zephyr"``).  When ``None`` the generator's ``OS`` class
                constant is used, falling back to ``"raspbian"``.

        Returns:
            A multi-line string with the runtime check, or ``""`` when
            the model has no CONSTRAINT blocks.
        """
        constraints = list(getattr(model, "constraints", []) or [])
        if not constraints:
            return ""

        resolved_backend = backend or self.OS or "raspbian"
        model_name = getattr(getattr(model, "metadata", None), "name", "device")
        funcs = self._get_constraint_functions()

        header = [
            f"# Runtime constraint check for '{model_name}'",
            f"# Backend: {resolved_backend}",
            f"# Helpers: {', '.join(sorted(funcs))}",
            "",
        ]

        if resolved_backend == "raspbian":
            return "\n".join(header + self._emit_python_runtime_check(constraints))
        if resolved_backend in ("riotos", "zephyr"):
            return "\n".join(header + self._emit_c_runtime_check(constraints))
        raise ValueError(f"Unsupported backend for constraint runtime check: {resolved_backend!r}")

    def _emit_python_runtime_check(self, constraints: List[Any]) -> List[str]:
        """Build the Python ``check_constraints()`` body line-by-line."""
        lines = [
            "def check_constraints():",
            '    """Run all declared CONSTRAINTs and return the failure count."""',
            "    constraint_failures = 0",
        ]
        for c in constraints:
            pred = self.render_constraint_predicate(c, "raspbian")
            message = getattr(c, "message", "") or "expression is false"
            lines.extend(
                [
                    f"    # {c.name}: {message}",
                    f"    if not ({pred}):",
                    "        constraint_failures += 1",
                ]
            )
        lines.append("    return constraint_failures")
        return lines

    def _emit_c_runtime_check(self, constraints: List[Any]) -> List[str]:
        """Build the C ``check_constraints()`` body line-by-line."""
        lines = [
            "void check_constraints(void) {",
            "    static uint32_t constraint_failures = 0;",
        ]
        for c in constraints:
            pred = self.render_constraint_predicate(c, "riotos")
            message = getattr(c, "message", "") or "expression is false"
            lines.extend(
                [
                    f"    /* {c.name}: {message} */",
                    f"    if (!({pred})) {{",
                    "        constraint_failures++;",
                    "    }",
                ]
            )
        lines.append("}")
        return lines

    def render_constraint_predicate(self, constraint, backend: str) -> str:
        """Render a UserConstraint predicate for the requested backend.

        Args:
            constraint: A parsed ``UserConstraint`` instance.
            backend: One of ``"raspbian"`` (Python), ``"riotos"`` (C),
                ``"zephyr"`` (C).

        Returns:
            The predicate as a Python or C expression string.

        Raises:
            ValueError: When ``backend`` is not a recognised target.
        """
        if backend == "raspbian":
            return self._render_python_predicate(constraint)
        if backend in ("riotos", "zephyr"):
            return self._render_c_predicate(constraint)
        raise ValueError(f"Unsupported backend for constraint predicate: {backend!r}")

    def _render_python_predicate(self, constraint) -> str:
        """Render a UserConstraint as a Python boolean expression.

        The output is a parenthesised Python expression.  Function calls
        keep their DSL name (e.g. ``count("SENSOR") < 10``) so the
        generated runtime helpers can be plain Python callables.
        """
        expr = getattr(constraint, "expr", None)
        if expr is None:
            return "True"
        cls = type(expr).__name__
        # ComparisonExpr (or its alias ConstraintExpr).
        if cls in ("ComparisonExpr", "ConstraintExpr"):
            left = self._render_python_atom(expr.left)
            right = self._render_python_atom(expr.right)
            return f"({left}) {expr.op} ({right})"
        # Anything that collapsed straight to an atom: just render it.
        return self._render_python_atom(expr)

    def _render_c_predicate(self, constraint) -> str:
        """Render a UserConstraint as a C boolean expression.

        Function calls are mapped through :meth:`_get_constraint_functions`
        and receive the per-kind integer code as their argument.
        """
        expr = getattr(constraint, "expr", None)
        if expr is None:
            return "1"
        cls = type(expr).__name__
        if cls in ("ComparisonExpr", "ConstraintExpr"):
            left = self._render_c_atom(expr.left)
            right = self._render_c_atom(expr.right)
            return f"({left}) {expr.op} ({right})"
        return self._render_c_atom(expr)

    def _render_python_atom(self, node) -> str:
        """Recursively render a single constraint expression node in Python."""
        cls = type(node).__name__

        if cls == "FunctionCallExpr":
            return f'{node.func}("{node.arg}")'

        if cls == "AdditiveExpr":
            return self._render_python_binary(node)

        if cls == "MultiplicativeExpr":
            return self._render_python_binary(node)

        if cls == "UnaryExpr":
            return self._render_python_atom(self._unwrap_unary(node))

        if cls == "NumberLiteral":
            return self._format_python_number(node)

        if cls == "StringLiteral":
            return repr(node.value)

        if cls == "BoolLiteral":
            return "True" if node.value else "False"

        if cls == "PropertyAccessExpr":
            return self._render_python_property(node)

        # Unknown node type: keep codegen going with a safe placeholder.
        return "0"

    def _render_c_atom(self, node) -> str:
        """Recursively render a single constraint expression node in C."""
        cls = type(node).__name__

        if cls == "FunctionCallExpr":
            return self._render_c_function_call(node)

        if cls == "AdditiveExpr":
            return self._render_c_binary(node)

        if cls == "MultiplicativeExpr":
            return self._render_c_binary(node)

        if cls == "UnaryExpr":
            return self._render_c_atom(self._unwrap_unary(node))

        if cls == "NumberLiteral":
            return self._format_c_number(node)

        if cls == "StringLiteral":
            return f'"{node.value}"'

        if cls == "BoolLiteral":
            return "true" if node.value else "false"

        if cls == "PropertyAccessExpr":
            return self._render_c_property(node)

        # Unknown node type: keep codegen going with a safe placeholder.
        return "0"

    def _render_python_binary(self, node) -> str:
        """Render an AdditiveExpr or MultiplicativeExpr as a Python expression."""
        operands = node.operands
        operators = node.operators
        result = self._render_python_atom(operands[0])
        for i, op in enumerate(operators):
            right = self._render_python_atom(operands[i + 1])
            result = f"({result} {op} {right})"
        return result

    def _render_c_binary(self, node) -> str:
        """Render an AdditiveExpr or MultiplicativeExpr as a C expression."""
        operands = node.operands
        operators = node.operators
        result = self._render_c_atom(operands[0])
        for i, op in enumerate(operators):
            right = self._render_c_atom(operands[i + 1])
            result = f"({result} {op} {right})"
        return result

    def _render_c_function_call(self, node) -> str:
        """Render a FunctionCallExpr as ``<runtime_helper>(<kind_code>)``."""
        funcs = self._get_constraint_functions()
        func_name = funcs.get(node.func, node.func)
        kind_code = self._CONSTRAINT_KIND_CODES.get(node.arg, 0)
        return f"{func_name}({kind_code})"

    def _render_python_property(self, node) -> str:
        """Render a PropertyAccessExpr as a Python ``_registry`` lookup."""
        segments = list(getattr(node, "segments", []) or [])
        if len(segments) >= 2:
            return f'_registry["{segments[0]}"].get("{segments[1]}")'
        if segments:
            return f'_registry["{segments[0]}"]'
        return "0"

    def _render_c_property(self, node) -> str:
        """Render a PropertyAccessExpr in C (placeholder; T11-T13 may override)."""
        segments = list(getattr(node, "segments", []) or [])
        if len(segments) >= 2:
            return f"/* {segments[0]}.{segments[1]} */ 0"
        if segments:
            return f"/* {segments[0]} */ 0"
        return "0"

    def _format_python_number(self, node) -> str:
        """Render a NumberLiteral as a Python numeric literal.

        When a unit is attached we delegate to the user-constraints
        normaliser so the emitted runtime value matches the validator's
        canonical units.
        """
        raw_value = node.value
        unit = getattr(node, "unit", None)
        if unit:
            normalised = self._normalize_constraint_value(raw_value, unit)
            if normalised is not None:
                return repr(normalised)
        try:
            return repr(float(raw_value))
        except (TypeError, ValueError):
            return str(raw_value)

    def _format_c_number(self, node) -> str:
        """Render a NumberLiteral as a C float literal."""
        raw_value = node.value
        unit = getattr(node, "unit", None)
        value: Any
        if unit:
            normalised = self._normalize_constraint_value(raw_value, unit)
            value = normalised if normalised is not None else raw_value
        else:
            value = raw_value
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return str(value)
        if numeric != numeric:  # NaN
            return "0.0f"
        if numeric == int(numeric) and abs(numeric) < 1e15:
            return f"{int(numeric)}.0f"
        return f"{numeric}f"

    @staticmethod
    def _unwrap_unary(node):
        """Return the inner expression wrapped by a ``UnaryExpr``.

        textX may collapse the ``UnaryExpr`` rule at parse time, in
        which case ``node`` is already the inner expression.  When the
        rule is preserved we try the common attribute names produced by
        textX for a single-child rule.
        """
        if type(node).__name__ != "UnaryExpr":
            return node
        for attr in ("expr", "multiplicative", "multiplicativeExpr", "operand", "value"):
            inner = getattr(node, attr, None)
            if inner is not None:
                return inner
        return node

    @staticmethod
    def _normalize_constraint_value(value: Any, unit: str) -> Optional[float]:
        """Normalise a ``(value, unit)`` pair to the validator's canonical unit.

        Wraps the validator helper in a lazy import to avoid an import
        cycle at module load time.  Returns ``None`` when the unit is
        unrecognised so callers can fall back to a raw literal.
        """
        try:
            from demol.lang.semantics.validators.user_constraints import (
                _normalize_value_with_unit,
            )
        except ImportError:
            return None
        try:
            normalised: Any = _normalize_value_with_unit(value, unit)
        except (ValueError, TypeError):
            return None
        try:
            return float(normalised)
        except (TypeError, ValueError):
            return None
