"""Model-to-Text transformation for Zephyr RTOS devices.

This module provides functionality to transform DeMoL device models into a
Zephyr application directory structure. It renders the project layout
expected by ``west build`` and the Zephyr CMake package:

    app/CMakeLists.txt
    app/prj.conf
    app/src/main.c
    app/boards/<board>.overlay
    app/dts/bindings/.gitkeep

Kconfig options are derived from the ``DEPENDENCIES`` block of every
``.hwd`` peripheral referenced by the model. The devicetree overlay is
emitted for every I2C peripheral with its bus, address, and compatible
string. The CMake target list is built from peripheral source names
and the Zephyr board name is resolved via :class:`BoardNameRegistry`.
"""

import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

import jinja2

from demol.definitions import TEMPLATES_ZEPHYR
from .base_generator import BaseCodeGenerator
from .board_registry import BoardNameRegistry
from ._template_mapper import PeripheralTemplateMapper

__all__ = ["ZephyrCodeGenerator", "m2t_zephyr"]


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# Default trigger-echo timeout (30 ms) -- well above the 4 m round-trip
# budget at 340 m/s, and a safe upper bound for HC-SR04 / SRF04 / SRF05
# ranging cycles. Peripheral templates forward this as the
# ``timeout_us`` argument of the shared ``trigger_echo_read`` macro.
_TRIGGER_ECHO_DEFAULT_TIMEOUT_US = 30000


def _strip_zephyr_template_suffix(template: str) -> str:
    """Strip the ``.c.j2`` / ``.j2`` suffix from a Zephyr template name.

    Example: ``"srf05.c.j2"`` -> ``"srf05"``. The base name is what the
    Zephyr generator feeds into ``app/src/<base>.c``.
    """
    base = template
    if base.endswith(".c.j2"):
        base = base[:-5]
    elif base.endswith(".j2"):
        base = base[:-3]
    return base


_APP_SRC_MAIN_C = """\
/*
 * Zephyr application entry point.
 * Generated by demol -- driver logic is added in a later task.
 */

#include <zephyr/kernel.h>

int main(void)
{
        return 0;
}
"""


# T16: MQTT client skeleton.  Replaces the static ``_APP_SRC_MAIN_C``
# body when the model declares at least one MQTT broker.  The block is
# intentionally minimal: client struct declaration, ``mqtt_init()``
# function with a TODO skeleton, and a call to ``mqtt_init()`` from
# ``main()``.  The full publish loop and TLS handshake are deferred to
# T17+.
_MQTT_APP_MAIN_C = """\
/*
 * Zephyr application entry point.
 * Generated by demol -- driver logic is added in a later task.
 */

#include <zephyr/kernel.h>
#include <zephyr/net/mqtt.h>
#include <zephyr/net/socket.h>

static struct mqtt_client client;

static void mqtt_init(void)
{
        /* T16 skeleton: broker.connect, client.init.
         * Full publish loop is implemented in a later task.
         */
}

int main(void)
{
        mqtt_init();
        return 0;
}
"""


def _i2c_compat_for(peripheral_name: str) -> str:
    """Build a devicetree ``compatible`` string for a peripheral.

    Zephyr convention is ``vendor,part`` lowercased. The BME680 has a
    well-known ``bosch,bme680`` binding; other peripherals fall back to
    their lowercased component name which downstream bindings may match
    on the ``,<part>`` token.
    """
    lowered = peripheral_name.lower()
    if lowered == "bme680":
        return "bosch,bme680"
    if lowered == "bme280":
        return "bosch,bme280"
    if lowered == "bh1750":
        return "rohm,bh1750"
    return lowered


class ZephyrCodeGenerator(BaseCodeGenerator):
    """Generates a Zephyr application from a DeMoL device model."""

    OS = "zephyr"

    def os_name(self) -> str:
        return self.OS

    def __init__(self, device_model, output_dir: Path, board_override: Optional[str] = None):
        """Initialize code generator with device model and output directory.

        Args:
            device_model: Parsed textX device model.
            output_dir: Output directory for generated code. The Zephyr
                application tree is written under ``<output_dir>/app/``.
            board_override: Optional explicit Zephyr board name; when
                provided, takes precedence over both the ``.hwd``
                ``PLATFORMS`` block and :class:`BoardNameRegistry`.
        """
        super().__init__(device_model, output_dir)
        self.env = self.setup_template_environment()
        self._registry = BoardNameRegistry()
        self._board_override = board_override

    def setup_template_environment(self) -> jinja2.Environment:
        """Setup Jinja2 environment with Zephyr-specific templates.

        ``trim_blocks`` / ``lstrip_blocks`` strip the leading whitespace
        the Jinja control lines would otherwise leave in the rendered
        artifacts.
        """
        fsloader = jinja2.FileSystemLoader(TEMPLATES_ZEPHYR)
        return jinja2.Environment(
            loader=fsloader,
            trim_blocks=True,
            lstrip_blocks=True,
        )

    def build_global_context(self) -> Dict[str, Any]:
        """Build the global Jinja context for Zephyr templates.

        Returns:
            Context with board name, peripheral sources, I2C overlay
            nodes, Kconfig symbols, and MQTT broker descriptors derived
            from the model. The ``mqtt_brokers`` list is empty when no
            MQTT broker is declared -- templates guard on it.
        """
        mqtt_brokers = self._collect_mqtt_brokers()
        return {
            "device_name": self.device_model.metadata.name,
            "board_name": self._resolve_board_name(),
            "sources": self._collect_source_names(),
            "i2c_nodes": self._collect_i2c_nodes(),
            "kconfig": self._collect_kconfig(),
            "mqtt_brokers": mqtt_brokers,
        }

    def _resolve_board_name(self) -> str:
        """Resolve the model board to a Zephyr target board name.

        Order of precedence:

        1. Explicit ``board_override`` argument (CLI ``--board`` flag).
        2. ``PLATFORMS.zephyr.board`` attribute in the ``.hwd`` board
           file (per-board override, mirrors the ``riotos.board``
           pattern used in :mod:`m2t_riot`).
        3. :class:`BoardNameRegistry` lookup for the DeMoL board name.
        4. Lowercased DeMoL board name (registry fallback).
        """
        if self._board_override:
            return self._board_override
        board = self.get_board()
        platform_attrs = self.get_platform_attributes(board, self.OS)
        if "board" in platform_attrs:
            return str(platform_attrs["board"])
        return self._registry.resolve(board.name, self.OS)

    def _collect_kconfig(self) -> Dict[str, str]:
        """Collect Kconfig symbols from every connected peripheral.

        Walks each connection, looks up the peripheral type, and emits
        ``CONFIG_<UPPER>`` symbols for every string dependency declared
        in the matching ``.hwd`` ``DEPENDENCIES`` block. Existing keys
        are preserved (``y`` is sticky once set).
        """
        kconfig: Dict[str, str] = {}
        for conn in self.get_connections():
            try:
                peripheral = conn.peripheral.ref
            except AttributeError:
                continue
            deps = getattr(peripheral, "dependencies", None) or []
            for dep in deps:
                target_os = getattr(dep, "target", None)
                if target_os is None or str(target_os).lower() != self.OS:
                    continue
                for item in getattr(dep, "items", []) or []:
                    name = self._dep_item_name(item)
                    if not name:
                        continue
                    kconfig.setdefault(name.upper(), "y")
        return kconfig

    def _collect_mqtt_brokers(self) -> List[Dict[str, Any]]:
        """Collect descriptors for every MQTT broker declared in the model.

        Returns a list of dicts -- one per ``MQTTBroker`` declaration. Each
        dict exposes the broker's name, host, port, and (optional)
        plain-text credentials. Non-MQTT brokers (AMQP / Redis) are
        skipped -- T16 only wires the MQTT client stack.

        The list is empty when no MQTT broker is declared; templates
        guard on it for backward compatibility.
        """
        result: List[Dict[str, Any]] = []
        for broker in self.get_brokers():
            if type(broker).__name__ != "MQTTBroker":
                continue
            username: Optional[str] = None
            password: Optional[str] = None
            auth = getattr(broker, "auth", None)
            auth_type = type(auth).__name__ if auth is not None else "AuthNone"
            if auth_type == "AuthPlain":
                username = getattr(auth, "username", None)
                password = getattr(auth, "password", None)
            result.append(
                {
                    "name": str(getattr(broker, "name", "")),
                    "host": str(getattr(broker, "host", "")),
                    "port": int(getattr(broker, "port", 1883) or 1883),
                    "ssl": bool(getattr(broker, "ssl", False)),
                    "username": username,
                    "password": password,
                }
            )
        return result



    def _collect_alerts(self) -> List[Dict[str, Any]]:
        """Build the ALERT trigger rendering context for ``main.c.j2``.

        Walks every ``ALERT`` block declared on the model and emits one
        descriptor dict per alert with keys: ``name`` (str), ``peripheral``
        (lowercased component type name, matches the .c driver base),
        ``condition_c`` (rendered C boolean expression, or ``None`` when the
        property resolver is empty / the condition references an unknown
        property), ``cooldown_ms`` (integer milliseconds), ``action`` (``"publish"``
        or ``"activate"``) and ``topic`` (the MQTT topic for ``publish`` actions,
        the subscribed CONNECT topic for ``activate`` actions).

        Returns an empty list when the model declares no ALERTs. Alerts whose
        condition cannot be rendered are dropped with a ``logger.warning`` to
        keep the generated code honest about what the driver actually exposes;
        ACTIVATE actions whose target has no CONNECT topic are downgraded to a
        warning (the runtime cannot route a payload to a disconnected target).
        """
        alerts = getattr(self.device_model, "alerts", None) or []
        if not alerts:
            return []
        result: List[Dict[str, Any]] = []
        for a in alerts:
            source = getattr(a, "source", None)
            source_name = getattr(source, "name", None) if source else None
            pref = getattr(source, "ref", None) if source else None
            if not source_name or pref is None:
                logger.warning(
                    "Zephyr alert '%s' dropped: source peripheral is unresolved.",
                    getattr(a, "name", "?"),
                )
                continue
            resolver = self.get_alert_property_resolver(pref, target="zephyr")
            if not resolver:
                logger.warning(
                    "Zephyr alert '%s' dropped: peripheral '%s' has no PROPERTIES "
                    "block declaring zephyr targets. Add PROPERTIES to the .hwd "
                    "to enable Zephyr alert codegen.",
                    a.name,
                    source_name,
                    type(pref).__name__,
                )
                continue
            condition_c = self.render_riot_condition(a.condition, resolver)
            if condition_c is None:
                logger.warning(
                    "Zephyr alert '%s' dropped: condition references a property "
                    "not declared in PROPERTIES (resolver=%s).",
                    a.name,
                    sorted(resolver.keys()),
                )
                continue
            cooldown_sec = self.cooldown_to_seconds(
                getattr(a, "cooldown", None), getattr(a, "cooldown_unit", None)
            )
            cooldown_ms = int(cooldown_sec * 1000)
            actions = getattr(a, "actions", None) or []
            for act in actions:
                kind = type(act).__name__
                if kind == "AlertPublish":
                    result.append(
                        {
                            "name": a.name,
                            "peripheral": str(getattr(pref, "name", "")).lower(),
                            "condition_c": condition_c,
                            "cooldown_ms": cooldown_ms,
                            "action": "publish",
                            "topic": getattr(act, "topic", ""),
                        }
                    )
                elif kind == "AlertActivate":
                    target_topic = self.resolve_activate_target_topic(act.target)
                    if not target_topic:
                        logger.warning(
                            "Zephyr alert '%s' ACTIVATE action skipped: target '%s' "
                            "has no CONNECT topic.",
                            a.name,
                            getattr(act.target, "name", "?"),
                        )
                        continue
                    result.append(
                        {
                            "name": a.name,
                            "peripheral": str(getattr(pref, "name", "")).lower(),
                            "condition_c": condition_c,
                            "cooldown_ms": cooldown_ms,
                            "action": "activate",
                            "topic": target_topic,
                        }
                    )
                else:
                    logger.warning(
                        "Zephyr alert '%s' has unknown action kind '%s' -- skipped.",
                        a.name,
                        kind,
                    )
        return result

    def _collect_samplings(self) -> List[Dict[str, Any]]:

        """Build the sampling-loop rendering context for ``main.c.j2``.



        Walks every SAMPLING block declared on the model and emits one

        descriptor dict per sampling.  The ``peripheral`` key is the

        lowercased component type name (e.g. ``"bme680"``) -- it matches

        the base name of the per-peripheral driver template, so the

        generated loop calls the matching ``<peripheral>_read()``

        function emitted by ``app/src/<peripheral>.c``.



        Each entry has keys: ``peripheral`` (str), ``rate`` (int Hz),

        ``mode`` (one of ``continuous`` / ``on_change`` / ``batch`` /

        ``on_demand``), ``period_ms`` (the ``k_msleep`` divisor,

        ``max(1, 1000 // rate_hz)``), and ``buffer_size`` (the integer

        batch length -- only meaningful in ``batch`` mode).  Returns

        an empty list when the model declares no SAMPLINGs (the

        template's ``{% if samplings %}`` guard preserves the static

        skeleton for backward compat).

        """

        samplings = getattr(self.device_model, "samplings", None) or []

        if not samplings:

            return []



        result: List[Dict[str, Any]] = []

        for s in samplings:

            target = getattr(s, "target", None)

            ref = getattr(target, "ref", None) if target else None

            type_name = getattr(ref, "name", None) if ref else None

            if not type_name:

                # Malformed / unresolved sampling -- skip rather than

                # crash; grammar / validators should already have caught it.

                continue

            rate = float(getattr(s, "rate", 1) or 1)

            rate_unit = getattr(s, "rate_unit", None)

            unit = str(rate_unit).lower() if rate_unit else "hz"

            multiplier = self._FREQ_UNIT_TO_HZ.get(unit, 1.0)

            rate_hz = int(rate * multiplier) if rate * multiplier >= 1 else 1

            if rate_hz < 1:

                rate_hz = 1

            period_ms = max(1, 1000 // rate_hz)

            mode = str(getattr(s, "mode", "continuous") or "continuous")

            buffer_size = int(getattr(s, "buffer", 10) or 10)

            result.append(

                {

                    "peripheral": str(type_name).lower(),

                    "rate": rate_hz,

                    "mode": mode,

                    "period_ms": period_ms,

                    "buffer_size": buffer_size,

                }

            )

        return result

    @staticmethod
    def _dep_item_name(item: Any) -> str:
        """Extract a string dependency name from a ``DependencyItem``.

        ``DependencyItem`` is either a bare ``STRING`` token (e.g. the
        ``"bme680"`` in ``zephyr=["bme680"]``) or a ``DependencyObject``
        dict-like with ``name``, ``version``, ``source`` attributes. Only
        the bare token form is emitted as a Kconfig symbol -- version /
        source dicts are packaging hints for package managers.
        """
        if isinstance(item, str):
            return item
        name = getattr(item, "name", None)
        if name:
            return str(name)
        return ""

    def _collect_i2c_nodes(self) -> List[Dict[str, Any]]:
        """Build the devicetree I2C overlay node list.

        Each I2C-connected peripheral contributes one entry with
        ``bus``, ``name``, ``addr``, and ``compat`` keys. The bus
        identifier is derived from the I2C pin function suffix
        (``sda-0``/``scl-0`` → ``i2c0``) so the overlay binds to the
        same bus the pin function references.
        """
        nodes: List[Dict[str, Any]] = []
        for conn in self.get_connections():
            data_conns = getattr(conn, "dataConns", None) or []
            for data in data_conns:
                if getattr(data, "type", None) != "i2c":
                    continue
                addr = self._extract_i2c_address(data)
                if not addr:
                    continue
                bus = self._i2c_bus_for(data)
                peripheral_name = self._peripheral_short_name(conn)
                if not peripheral_name:
                    continue
                nodes.append(
                    {
                        "bus": bus,
                        "name": peripheral_name.lower(),
                        "addr": addr,
                        "compat": _i2c_compat_for(peripheral_name),
                    }
                )
        return nodes

    @staticmethod
    def _extract_i2c_address(data_conn: Any) -> str:
        """Return the I2C slave address in hex (e.g. ``0x76``) or empty."""
        props = getattr(data_conn, "props", None) or []
        for p in props:
            if getattr(p, "name", None) == "slave_address":
                val = p.value
                if isinstance(val, int):
                    return f"0x{val:02x}"
                return str(val)
        return ""

    @staticmethod
    def _i2c_bus_for(data_conn: Any) -> str:
        """Derive the devicetree bus label from the I2C pin function.

        ``sda-0``/``scl-0`` → ``i2c0``; defaults to ``i2c0`` when no
        pin function hint is present.
        """
        pins = getattr(data_conn, "pins", None) or []
        for pin in pins:
            func = getattr(pin, "function", "") or ""
            if func and "-" in func:
                suffix = func.split("-", 1)[1]
                if suffix.isdigit():
                    return f"i2c{suffix}"
        return "i2c0"

    @staticmethod
    def _peripheral_short_name(conn: Any) -> str:
        """Return the peripheral's component name."""
        try:
            ref = conn.peripheral.ref
            name = getattr(ref, "name", None) or getattr(conn.peripheral, "name", None)
        except AttributeError:
            name = None
        return str(name) if name else ""

    def _collect_source_names(self) -> List[str]:
        """Collect peripheral source names for the CMake target list.

        Includes ``main`` (the application entry point) plus a
        lowercased peripheral identifier for every connected peripheral
        that has a Zephyr template declared in its ``.hwd`` ``TEMPLATES``
        block.
        """
        sources: List[str] = ["main"]
        for conn in self.get_connections():
            try:
                peripheral = conn.peripheral.ref
            except AttributeError:
                continue
            templates = getattr(peripheral, "templates", None) or []
            has_zephyr = any(str(getattr(t, "os", "")).lower() == self.OS for t in templates)
            if not has_zephyr:
                continue
            name = getattr(peripheral, "name", None)
            if not name:
                continue
            sources.append(str(name).lower())
        return sources

    def _render_kconfig(self) -> str:
        """Render ``app/prj.conf`` from the collected Kconfig symbols.

        When the model declares an MQTT broker, the template appends the
        Zephyr network + MQTT client stack symbols. A model with no MQTT
        broker produces a ``prj.conf`` with no MQTT footprint.
        """
        template = self.env.get_template("prj.conf.j2")
        return template.render(
            kconfig=self._collect_kconfig(),
            mqtt_brokers=self._collect_mqtt_brokers(),
        )

    def _render_devicetree(self) -> str:
        """Render ``app/boards/<board>.overlay`` from the I2C node list."""
        template = self.env.get_template("app.overlay.j2")
        return template.render(i2c_nodes=self._collect_i2c_nodes())

    def _render_cmakelists(self) -> str:
        """Render ``app/CMakeLists.txt`` for the resolved Zephyr board."""
        template = self.env.get_template("CMakeLists.txt.j2")
        return template.render(
            board_name=self._resolve_board_name(),
            sources=self._collect_source_names(),
        )

    def _render_main_c(self) -> str:
        """Return the ``app/src/main.c`` body.

        Four branches, in priority order:

        1. Model declares >= 1 ALERT -> render the Jinja2 ``main.c.j2``
           template with the collected alerts. The template emits a
           ``void check_alerts(void)`` function and calls it from a
           main loop. PUBLISH actions emit a ``LOG_INF`` placeholder
           (full MQTT publish is owned by T16); ACTIVATE actions emit a
           ``gpio_pin_set_dt`` placeholder.
        2. Model declares >= 1 SAMPLING block -> render the same template
           with sampling entries. Each sampling entry has keys
           ``peripheral``, ``rate``, ``mode``, ``period_ms`` and
           ``buffer_size``; the template emits a deterministic
           ``while (1) { k_msleep(period); read_<peripheral>(); }`` loop.
        3. Model declares >= 1 MQTT broker (and no ALERTs / SAMPLINGs) ->
           emit the MQTT-flavoured skeleton (``_MQTT_APP_MAIN_C``) which
           wires ``mqtt_init()`` into ``main()``.  The full publish loop
           is deferred to T17+.
        4. Otherwise -> the static ``_APP_SRC_MAIN_C`` skeleton (byte-
           identical to the pre-T14 output, so existing golden snapshots
           for non-ALERT / non-SAMPLING / non-MQTT examples stay stable).
        """
        alerts = self._collect_alerts()
        samplings = self._collect_samplings()
        if alerts or samplings:
            min_period_ms = min(s["period_ms"] for s in samplings) if samplings else 1000
            template = self.env.get_template("main.c.j2")
            return template.render(
                alerts=alerts,
                samplings=samplings,
                min_period_ms=min_period_ms,
            )
        if self._collect_mqtt_brokers():
            return _MQTT_APP_MAIN_C
        return _APP_SRC_MAIN_C
    def _render_peripheral_drivers(self, app_src_dir: Path) -> None:
        """Render per-peripheral driver templates to ``app/src/<base>.c``."""
        board = self.get_board()
        for i, conn in enumerate(self.get_connections()):
            try:
                pref = conn.peripheral.ref
            except AttributeError:
                continue
            tmpl = PeripheralTemplateMapper.get_template(pref, self.OS)
            if not tmpl:
                continue
            base_name = _strip_zephyr_template_suffix(tmpl)

            pins = self.get_pin_mappings(conn, board)
            conn_info = self._build_conn_info(pins, board)

            attributes = self.get_peripheral_attributes(pref)
            context: Dict[str, Any] = {
                "name": base_name,
                "instance": conn.peripheral.name,
                "index": i,
                "conn": conn_info,
                "attributes": attributes,
                "timeout_us": _TRIGGER_ECHO_DEFAULT_TIMEOUT_US,
            }

            gpio_pins = conn_info.get("gpio", {}).get("pins", {}) if "gpio" in conn_info else {}
            if "trigger" in gpio_pins and "echo" in gpio_pins:
                context["trig"] = gpio_pins["trigger"]["name"]
                context["echo"] = gpio_pins["echo"]["name"]

            try:
                template = self.env.get_template(tmpl)
            except jinja2.TemplateNotFound:
                logger.warning(
                    "Zephyr driver template '%s' not found for peripheral '%s'; skipping.",
                    tmpl,
                    type(pref).__name__,
                )
                continue

            self._write_template(template, context, app_src_dir / f"{base_name}.c")
            logger.debug("Generated Zephyr driver: %s", base_name)

    def _collect_constraints(self) -> List[Dict[str, str]]:
        """Build the constraint-rendering context for Zephyr templates.

        Each entry has ``name`` (DSL name), ``message`` (the MESSAGE string,
        or a default), ``predicate_func`` (a C identifier for the predicate),
        and ``predicate_c`` (a C boolean expression evaluating the constraint).
        Returns an empty list when the model declares no CONSTRAINTs.
        """
        constraints = getattr(self.device_model, "constraints", None) or []
        if not constraints:
            return []

        result: List[Dict[str, str]] = []
        for c in constraints:
            name = str(getattr(c, "name", "")) or "unnamed"
            message = getattr(c, "message", None) or "expression is false"
            expr = getattr(c, "expr", None)
            predicate_c = self._render_zephyr_predicate(expr) if expr is not None else "true"
            result.append(
                {
                    "name": name,
                    "message": message,
                    "predicate_func": f"_eval_constraint_{name}",
                    "predicate_c": predicate_c,
                }
            )
        return result

    @staticmethod
    def _zephyr_kind_code(arg: Any) -> Optional[str]:
        """Map a CONSTRAINT ``FunctionArg`` to the matching runtime helper.

        Returns the C expression to use in a predicate, or None when the
        argument is not a known aggregate. The mapping mirrors design doc section 4.1.
        """
        if arg is None:
            return None
        arg_norm = str(arg).upper()
        if arg_norm == "SENSOR":
            return "_count_kind(DEMOL_KIND_SENSOR)"
        if arg_norm == "ACTUATOR":
            return "_count_kind(DEMOL_KIND_ACTUATOR)"
        if arg_norm == "PERIPHERAL":
            return "_device_count"
        if arg_norm == "CONNECTION":
            return "_count_connected()"
        return None

    @staticmethod
    def _zephyr_unit_multiplier(unit: Any) -> float:
        """Normalize a constraint numeric literal to its base unit.

        Returns the multiplier for the unit suffix (or 1.0 when no unit is
        given). Power is normalised to mW, current to mA, capacity to mAh,
        frequency to Hz, matching the runtime helpers expected units.
        """
        if unit is None:
            return 1.0
        u = str(unit).lower()
        table = {
            "w": 1000.0, "mw": 1.0, "uw": 0.001,
            "a": 1000.0, "ma": 1.0, "ua": 0.001,
            "ah": 1000.0, "mah": 1.0,
            "hz": 1.0, "khz": 1e3, "mhz": 1e6, "ghz": 1e9,
        }
        return table.get(u, 1.0)

    def _render_zephyr_expr(self, node: Any) -> str:
        """Render a constraint expression AST node as a C int expression.

        Walks the textX AST and emits a C snippet using the runtime helpers.
        Returns ``"0"`` (predicate is always false) for unsupported node types;
        a warning is logged so the operator can fix the offending constraint.
        """
        if node is None:
            return "0"
        cls = type(node).__name__

        if cls == "FunctionCallExpr":
            func = str(getattr(node, "func", "")).lower()
            arg = getattr(node, "arg", None)
            if func in ("sum_power", "max_power", "avg_power"):
                kind_code = self._zephyr_kind_code(arg)
                if kind_code is None:
                    logger.warning("Unsupported %s argument: %r", func, arg)
                    return "0"
                if func == "sum_power":
                    return "_sum_power_mW()"
                if func == "max_power":
                    return "_max_power_mW()"
                # avg_power: avoid division by zero at runtime
                return f"((({kind_code}) > 0) ? (((int32_t)_sum_power_mW()) / ({kind_code})) : 0)"
            if func == "count":
                kind_code = self._zephyr_kind_code(arg)
                if kind_code is None:
                    logger.warning("Unsupported count argument: %r", arg)
                    return "0"
                return f"(int32_t)({kind_code})"
            logger.warning("Unknown built-in function: %r", func)
            return "0"

        if cls == "NumberLiteral":
            value = float(getattr(node, "value", 0) or 0)
            unit = getattr(node, "unit", None)
            scaled = value * self._zephyr_unit_multiplier(unit)
            if scaled == int(scaled):
                return f"{int(scaled)}"
            return f"{scaled:.6f}"

        if cls == "StringLiteral":
            return '"' + str(getattr(node, "value", "")).replace('"', '\\"') + '"'

        if cls == "BoolLiteral":
            return "true" if getattr(node, "value", False) else "false"

        if cls == "PropertyAccessExpr":
            # Property access is resolved at validation time; at codegen time we
            # emit a stub that returns 0 with a logged warning.
            logger.warning("Property access in constraint is not yet supported at runtime.")
            return "0"

        if cls in ("AdditiveExpr", "MultiplicativeExpr"):
            operands = list(getattr(node, "operands", []) or [])
            operators = list(getattr(node, "operators", []) or [])
            if not operands:
                return "0"
            result = self._render_zephyr_expr(operands[0])
            for op, rhs in zip(operators, operands[1:]):
                result = f"(({result}) {op} ({self._render_zephyr_expr(rhs)}))"
            return result

        logger.warning("Unsupported constraint expression node type: %s", cls)
        return "0"

    def _render_zephyr_predicate(self, expr: Any) -> str:
        """Render a ConstraintExpr as a C boolean expression.

        The grammar constrains ConstraintExpr to a single ComparisonExpr, so
        the fast path handles that case directly. Falls back to the generic
        AST walker when textX collapses the rule.
        """
        if expr is None:
            return "true"
        cls = type(expr).__name__
        if cls == "ComparisonExpr":
            left = self._render_zephyr_expr(getattr(expr, "left", None))
            op = str(getattr(expr, "op", "=="))
            right = self._render_zephyr_expr(getattr(expr, "right", None))
            return f"(({left}) {op} ({right}))"
        return self._render_zephyr_expr(expr)

    def _render_constraint_files(self, app_src_dir: Path) -> None:
        """Emit ``constraint.c`` and ``constraint.h`` when constraints exist.

        No-op when ``model.constraints`` is empty -- this is the
        backward-compat guard that keeps existing Zephyr apps without
        CONSTRAINTs untouched.
        """
        constraints = self._collect_constraints()
        if not constraints:
            return
        context = {
            "device_name": self.device_model.metadata.name,
            "constraints": constraints,
        }
        self._write_template(
            self.env.get_template("constraint.h.j2"),
            context,
            app_src_dir / "constraint.h",
        )
        self._write_template(
            self.env.get_template("constraint.c.j2"),
            context,
            app_src_dir / "constraint.c",
        )

    def _has_constraints(self) -> bool:
        """True when the model declares at least one CONSTRAINT."""
        return bool(getattr(self.device_model, "constraints", None))

    def generate(self) -> None:
        """Emit the Zephyr application tree.

        Writes:
            app/CMakeLists.txt
            app/prj.conf
            app/src/main.c
            app/src/constraint.{c,h}        (only when model has CONSTRAINTs)
            app/boards/<board>.overlay
            app/dts/bindings/.gitkeep
        """
        logger.info(
            "Generating Zephyr application for %s...",
            self.device_model.metadata.name,
        )

        app_dir = self.output_dir / "app"
        app_src_dir = app_dir / "src"
        app_boards_dir = app_dir / "boards"
        app_dts_bindings_dir = app_dir / "dts" / "bindings"

        board_name = self._resolve_board_name()
        has_constraints = self._has_constraints()

        app_dir.mkdir(parents=True, exist_ok=True)
        app_boards_dir.mkdir(parents=True, exist_ok=True)

        self._write_template(
            self.env.get_template("CMakeLists.txt.j2"),
            {
                "board_name": board_name,
                "sources": self._collect_source_names(),
                "has_constraints": has_constraints,
            },
            app_dir / "CMakeLists.txt",
        )
        self._write_template(
            self.env.get_template("prj.conf.j2"),
            {
                "kconfig": self._collect_kconfig(),
                "mqtt_brokers": self._collect_mqtt_brokers(),
            },
            app_dir / "prj.conf",
        )
        self._write_template(
            self.env.get_template("app.overlay.j2"),
            {"i2c_nodes": self._collect_i2c_nodes()},
            app_boards_dir / f"{board_name}.overlay",
        )

        app_src_dir.mkdir(parents=True, exist_ok=True)
        (app_src_dir / "main.c").write_text(self._render_main_c(), encoding="utf-8")

        self._render_peripheral_drivers(app_src_dir)
        self._render_constraint_files(app_src_dir)

        app_dts_bindings_dir.mkdir(parents=True, exist_ok=True)
        (app_dts_bindings_dir / ".gitkeep").write_text("", encoding="utf-8")

        logger.info("Zephyr code generation complete!")


def m2t_zephyr(model, output_dir=".", board_override: Optional[str] = None):
    """Transform a DeMoL device model object to a Zephyr application tree.

    Args:
        model: Parsed textX device model.
        output_dir: Output directory for the generated Zephyr app tree.
        board_override: Optional explicit Zephyr board name; bypasses
            the registry and the ``.hwd`` ``PLATFORMS`` attribute when
            provided.
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    generator = ZephyrCodeGenerator(model, output_path, board_override=board_override)
    generator.generate()
