"""Model-to-Text transformation for Zephyr RTOS devices.

This module provides functionality to transform DeMoL device models into a
Zephyr application directory structure. The skeleton emits the minimum
viable Zephyr project layout (CMakeLists.txt, prj.conf, src/main.c, a board
overlay, and a dts/bindings placeholder); Kconfig, devicetree overlays,
and per-peripheral driver templates are added in subsequent tasks
(Wave 2B / Task 2.2+).
"""

import logging
from pathlib import Path
from typing import Any, Dict

import jinja2

from demol.definitions import TEMPLATES_ZEPHYR
from .base_generator import BaseCodeGenerator

__all__ = ["ZephyrCodeGenerator"]


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# Static placeholders for the Wave 2A skeleton. Jinja2 rendering of
# CMakeLists.txt / prj.conf / devicetree overlays is introduced in Task 2.2.
_APP_CMAKELISTS_TXT = """\
# Minimal Zephyr application CMakeLists.txt
# Generated by demol — full template support added in a later task.

cmake_minimum_required(VERSION 3.20.0)

find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
project(demol_app)

target_sources(app PRIVATE src/main.c)
"""

_APP_PRJ_CONF = """\
# Generated by demol
# Kconfig options are emitted here in a later task.
"""

_APP_SRC_MAIN_C = """\
/*
 * Zephyr application entry point.
 * Generated by demol — driver logic is added in a later task.
 */

#include <zephyr/kernel.h>

int main(void)
{
        return 0;
}
"""

_APP_BOARDS_NATIVE_SIM_OVERLAY = """\
// Placeholder Zephyr devicetree overlay for the native_sim board.
// Per-peripheral overlays are emitted in a later task.
"""


class ZephyrCodeGenerator(BaseCodeGenerator):
    """Generates a Zephyr application skeleton from a device model.

    Wave 2A skeleton: emits the directory layout expected by the Zephyr
    build system. The peripheral driver code, Kconfig options, and
    devicetree overlays are added in subsequent tasks.
    """

    OS = "zephyr"

    def os_name(self) -> str:
        return self.OS

    def __init__(self, device_model, output_dir: Path):
        """Initialize code generator with device model and output directory.

        Args:
            device_model: Parsed textX device model.
            output_dir: Output directory for generated code. The Zephyr
                application tree is written under ``<output_dir>/app/``.
        """
        super().__init__(device_model, output_dir)
        self.env = self.setup_template_environment()

    def setup_template_environment(self) -> jinja2.Environment:
        """Setup Jinja2 environment with Zephyr-specific templates.

        Returns:
            Configured Jinja2 Environment. Currently empty; populated as
            Jinja2 templates are introduced in later tasks.
        """
        fsloader = jinja2.FileSystemLoader(TEMPLATES_ZEPHYR)
        return jinja2.Environment(loader=fsloader)

    def build_global_context(self) -> Dict[str, Any]:
        """Build the global Jinja context for Zephyr templates.

        Returns a minimal context for the skeleton. Expanded in Task 2.2
        with board name, broker config, peripheral connections, and
        Kconfig / devicetree payload.
        """
        return {
            "device_name": self.device_model.metadata.name,
        }

    def generate(self) -> None:
        """Emit the Zephyr application skeleton.

        Writes the minimum project layout expected by ``west build`` and
        the Zephyr CMake package:
            app/CMakeLists.txt
            app/prj.conf
            app/src/main.c
            app/boards/native_sim.overlay
            app/dts/bindings/.gitkeep
        """
        logger.info("Generating Zephyr application skeleton...")

        app_dir = self.output_dir / "app"
        app_src_dir = app_dir / "src"
        app_boards_dir = app_dir / "boards"
        app_dts_bindings_dir = app_dir / "dts" / "bindings"

        # Local helper: BaseCodeGenerator._write_template is Jinja2-only;
        # the skeleton writes static text directly.
        def _write(path: Path, content: str) -> None:
            path.parent.mkdir(parents=True, exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            logger.debug(f"Generated: {path}")

        _write(app_dir / "CMakeLists.txt", _APP_CMAKELISTS_TXT)
        _write(app_dir / "prj.conf", _APP_PRJ_CONF)
        _write(app_src_dir / "main.c", _APP_SRC_MAIN_C)
        _write(app_boards_dir / "native_sim.overlay", _APP_BOARDS_NATIVE_SIM_OVERLAY)
        _write(app_dts_bindings_dir / ".gitkeep", "")

        logger.info("Zephyr skeleton code generation complete!")


def m2t_zephyr(model, output_dir="."):
    """Transform a DeMoL device model object to a Zephyr application skeleton.

    Args:
        model: Parsed textX device model.
        output_dir: Output directory for the generated Zephyr app tree.
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    generator = ZephyrCodeGenerator(model, output_path)
    generator.generate()
