FROM python:3.9-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    libgpiod2 \
    i2c-tools \
    espeak-ng \
    espeak \
    alsa-utils \
    portaudio19-dev \
{% for dep in apt_dependencies %}
    {{ dep }} \
{% endfor %}
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install lgpio pigpio gpio gpiozero

COPY . .

# Default command
CMD ["python3"]
